features:
  versions:
    - HTTP_VERSION_2
  protocols:
    - PROTOCOL_GRPC
  codecs:
    - CODEC_PROTO
  compressions:
    - COMPRESSION_IDENTITY
  stream_types:
    - STREAM_TYPE_UNARY
  supports_h2c: true
  supports_tls: false
  supports_trailers: true
  supports_half_duplex_bidi_over_http1: false
  supports_connect_get: false
  supports_message_receive_limit: false
